### ISSUE TITLE
OLED wakeup call

### ISSUE THREAD

**Issue by JaniJL** [Dvogonen/cyclop_plus#10]
When using screen saver and the OLED is dimmed, it would be nice to just wake up OLED with one button press. Now if you press button, OLED wakes up, but also receiver jumps to next channel.

Very nice firmware for cyclops, thx a lot for your contribute to this hobby!

BR
Jani

**Comment by Dvogonen** [comment]
This sounds like a good idea. 
It will be on the list for 1.5.
