### ISSUE TITLE
brainstorming: head tracker

### ISSUE THREAD

**Issue by tigert** [Dvogonen/cyclop_plus#14]
Tjänare,

I am building myself a head tracker using and arduino nano and a sensor board:
- sensor board: http://www.banggood.com/GY-85-BMP085-Sensor-Module-9-Axis-6DOF-9DOF-IMU-Sensor-p-962801.html
- instruction thread: http://www.rcgroups.com/forums/showthread.php?t=1677559

Now, I do not have a Cyclops myself yet, but I was considering one mostly because of this project. 

I realized the sensor module is also wired via i2c, and I was wondering whether the cpu would have enough IO lines and memory/cycles to deal with this task as well..

Just in case the TODO-list might run empty :-)

**Comment by Dvogonen** [comment]
I missed this question. Sorry about that. 
I don't think that the Cyclops receiver board is the right place for the head tracker code. Although everything is possible, you would get yourself into a rather tricky situation where you would have to implement some sort of multitasking system that could handle both channel scanning and head tracking at the same time. And this on hardware that is running on half the speed of the slowest used in the project you linked to. 
Another issue is that you would have to bit bang I2C for either the screen or the sensor. Possible, but painful. 

I think that a much better idea would be to add both the sensor and the processor board of the headtracker system. There is absolutely room for it in the googles.
