### ISSUE TITLE
Battery voltage mod + changes

### ISSUE THREAD

**Issue by CurtisFissel** [Dvogonen/cyclop_plus#3]
I just got done doing a slight mod to my Cyclops Goggles. 
![2016-07-02 15 17 34](https://cloud.githubusercontent.com/assets/5514582/16542256/284a7634-406f-11e6-82e9-28936c9a07d5.jpg)

Added a voltage divider to A2 pin (A1 seems to be mislabeled? It actually goes to A3 so i just decided to use the correctly labeled A2) 

I'm using a 10K and 4.7K resistor for the voltage divider. But now that I realize this is a 3.3v based system that won't be good enough for 3s battery sensing. The resistor values are currently configurable in code I have written so anyone can choose a suitable divider for their application.

Open to suggestions of standardizing the resistor values to make it more noob friendly and reduce code complexity.

Still working on the code but figured I would open the discussion

Curtis

**Comment by CurtisFissel** [comment]
Did some work and added it to the main Channel Screen with a nice little icon and bar indicator. Also it flashes when under the last bar level.
![batt](https://cloud.githubusercontent.com/assets/5514582/16547307/2c61871c-4137-11e6-9af1-757f241eed41.gif)

Doesn't currently support 3s voltages(extra "1" digit) yet and the code is a little messy so im trying to fix that up.

**Comment by Dvogonen** [comment]
Thats looking really nice. I missed your comment so I started implemented a battery icon myself in the 1.3 dev branch. Yours look better than mine and is better placed, so I will gladly use that one if you finish the code.

I have also implemented an options menu for selecting alternatives like flipping the display, battery type, screen saver etc, etc. Have a peek in the 1.3 branch.

I think that the best idea is to specify exactly which resistance values to use. If someone feels confident to start changing those, they will probably have no problems changing the code.
To be able to use 3s, 2s as well as 9 volts batteries  I think that a 3 to 1 divider is optimal. A 3s battery will have a maximum voltage of around 12,6 volts 12,6/4 = 3.15. Very close to 3.3.
The standard cookbook rule is to use  a resistance of 10K for analog inputs. But I guess that that is intended for 5 volt sources. With a 3s battery we should use at least 30K. How about using a  22K and a 68K resistor? Standard values and with safety margin. It also makes it possible to use replace the 68K resistor with three 22K ones in series.

**Comment by MrChzl** [comment]
Yes, you can use a 30k/90k voltage divider. The higher the resistance the lower the current will be, which makes the measurement less exact. For 5v the school book example is to use a total resistance of 10k, but 100k also works. In this application we do not need to be very exact. 

The battery meter code in 1.3 is not finished and has had 0 testing, so I can not really comment on the behaviour.

**Comment by Dvogonen** [comment]
It turns out A1 (the real pin, not the mislabeled pad on the PCB)  is already wired so that it is possible to use it to read battery voltage. No divider is needed. The resolution is not optimal, but it works for a crude battery meter.  I have not heard from CurtisFissel in a while, so I am completing the code on my own.
I have committed the code in the 1.3 branch so this issue is closed

**Comment by CurtisFissel** [comment]
Hey sorry about that. Was crazy busy this week and just haven't had anytime to work on this.

Here is my code for the 2s battery and Beeper setup. 
[cyclop_plus.zip](https://github.com/Dvogonen/cyclop_plus/files/365870/cyclop_plus.zip)

Feel free to grab anything from it. I assume your code will be much cleaner though. 

Curtis
